export const CHANGE_SELECTED_PATH = 'CHANGE_SELECTED_PATH';
export const REMOVE_WAYPOINT = 'REMOVE_WAYPOINT';
export const SET_PATH_CONFIG = 'SET_PATH_CONFIG';
export const SET_WAYPOINT = 'SET_WAYPOINT';
export const ADD_WAYPOINT = 'ADD_WAYPOINT';
export const DELETE_PATH = 'DELETE_PATH';
export const RENAME_PATH = 'RENAME_PATH';
export const ADD_PATH = 'ADD_PATH';
