export const CHANGE_SELECTED_PATHS_GROUP = 'CHANGE_SELECTED_PATHS_GROUP';
export const RENAME_GROUP = 'RENAME_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const ADD_GROUP = 'ADD_GROUP';
