export const CHANGE_SELECTED_PATHS_GROUP = 'CHANGE_SELECTED_PATHS_GROUP';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const DELETE_GROUP = 'DELETE_GROUP';
export const REMOVE_PATH = 'REMOVE_PATH';
