export const SETTINGS_REDUCER = "SETTINGS_REDUCER";
export const FIELD_VIEW_REDUCER = "FIELD_VIEW_REDUCER";
export const TOOLS_REDUCER = "TOOLS_REDUCER";
export const APP_REDUCER = "APP_REDUCER";
export const WAYPOINT_INFO_REDUCER = "WAYPOINT_INFO_REDUCER";
export const PLAYING_BAR_REDUCER = "PLAYING_BAR_REDUCER";