export const CHANGE_LISTEN_TO_MOUSE_STATUS = 'CHANGE_LISTEN_TO_MOUSE_STATUS';
export const SET_DRAW_ROBOT_INTERVAL = 'SET_DRAW_ROBOT_INTERVAL';
export const CHANGE_RANGE_POSITION = 'CHANGE_RANGE_POSITION';
export const CHANGE_POPUPS_STATUS = 'CHANGE_POPUPS_STATUS';
